name: Check

on:
  push:
    branches:
      - "**"
jobs:
  publish-grp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
      - name: Set stages list
        id: set_stages
        shell: /usr/bin/bash -e {0}
        run: |
          if command -v awk &>/dev/null; then
              echo "awk is available"
          else
              echo "awk is not available"
          fi
          merged_branch=$(echo "${{ github.event.head_commit.message }}" | awk -F / '{ if($3) print $3 }' | grep -oE '[^/]+$')
          echo "$merged_branch"" > $GITHUB_OUTPUT

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo ${{ steps.set_stages.outputs.merged_branch }}
          echo "${{github.event.head_commit.id}}"
          echo "$GITHUB_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
