name: Check

on:
  push:
    branches:
      - "**"
jobs:
  publish-grp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
      - name: Set stages list
        id: set_stages
        shell: /usr/bin/bash -e {0}
        run: |
          set +e
          clean_message=$(echo "${{ github.event.head_commit.message }}" | sed 's/\s//g')
          echo "$clean_message"
          merged_branch=$(echo "$clean_message" | nawk -F / '{ if(NF>=3) print $3 }')
          echo "$merged_branch" >> $GITHUB_OUTPUT
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo ${{ steps.set_stages.outputs.merged_branch }}
          echo "${{github.event.head_commit.id}}"

      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
