name: Check

on:
  pull_request:
    branches:
      - master
    types:
      - closed
jobs:
  publish-grp:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
      - name: Set stages list
        id: set_stages
        run: |
          merged_branch=$(git log -1 --merges --pretty=format:"%s" 2>/dev/null | grep -oE '(?<=Merge pull request #[0-9]+ from ).*' | head -n 1)
          echo "$merged_branch" >> $GITHUB_OUTPUT
          echo "$merged_branch"
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
